// v2
var SERIES = [
  { id:'sax',      icon:'🎷', name:'Sax Series',        color:'#1a2e26', accent:'#3aaa7a', labelColor:'#3aaa7a', art:'https://pub-8a606f3e80df454aa140a9958d8abc6c.r2.dev/art-sax.png' },
  { id:'hiphop',   icon:'🎤', name:'Hip-Hop Series',     color:'#1a1a0e', accent:'#f58a13', labelColor:'#f58a13', art:'https://pub-8a606f3e80df454aa140a9958d8abc6c.r2.dev/art-hiphop.png' },
  { id:'function', icon:'🎛️', name:'EDM Series',         color:'#2d1a12', accent:'#e8723a', labelColor:'#e8723a', art:'https://pub-8a606f3e80df454aa140a9958d8abc6c.r2.dev/art-function.png' },
  { id:'open',     icon:'🎚️', name:'Open Format Series', color:'#12121a', accent:'#a07be8', labelColor:'#a07be8', art:'https://pub-8a606f3e80df454aa140a9958d8abc6c.r2.dev/art-open.png' },
  { id:'warmup',   icon:'⚡', name:'Warm-Up Mix Series', color:'#1a1a2e', accent:'#f58a13', labelColor:'#f58a13', art:'https://pub-8a606f3e80df454aa140a9958d8abc6c.r2.dev/art-warmupmix.png' }
];

var MIXES = [
  { id:1,  series:'sax',      title:'Max The Sax',         tags:['Pure Sax','High Energy','95–110 BPM','60 Min'],       price:'24.99', tracks:['DMX – Party Up','Usher – Yeah!','Jay-Z – Empire State of Mind','Kanye West – Gold Digger','Beyoncé – Crazy in Love','Mary J. Blige – Real Love','Biggie – Juicy','Ne-Yo – So Sick','Chris Brown – Forever','R. Kelly – Ignition','Alicia Keys – No One','Drake – One Dance','Nicki Minaj – Super Bass','T.I. – Whatever You Like','Rihanna – Only Girl','Flo Rida – Good Feeling','Pitbull – Give Me Everything','Lil Wayne – How to Love','Bruno Mars – Locked Out of Heaven','Maroon 5 – Moves Like Jagger','Kid Cudi – Pursuit of Happiness','Wiz Khalifa – Work Hard Play Hard'] },
  { id:2,  series:'sax',      title:'Sax On The Beach',    tags:['Beachy','Feel-Good','90–105 BPM','60 Min'],           price:'24.99', tracks:['Kool & The Gang – Get Down on It','Earth Wind & Fire – September','Michael Jackson – Don\'t Stop \'Til You Get Enough','Stevie Wonder – Sir Duke','Lionel Richie – All Night Long','Average White Band – Pick Up the Pieces','Grover Washington Jr. – Just the Two of Us','George Benson – Give Me the Night','James Brown – I Got You','Tower of Power – What Is Hip','Chic – Good Times','Herb Alpert – Rise','Bob James – Take Me to the Mardi Gras','David Sanborn – Hideaway','Spyro Gyra – Morning Dance','Patti LaBelle – Lady Marmalade','Al Jarreau – We\'re in This Love Together','Dave Grusin – Mountain Dance'] },
  { id:3,  series:'sax',      title:'Sax Mex',             tags:['Latin','Reggaeton','Sax','95–115 BPM','60 Min'],      price:'24.99', tracks:['Marc Anthony – Vivir Mi Vida','Bad Bunny – Tití Me Preguntó','J Balvin – Mi Gente','Daddy Yankee – Gasolina','Ozuna – Taki Taki','Maluma – Hawái','Shakira – Hips Don\'t Lie','Celia Cruz – La Vida Es Un Carnaval','Enrique Iglesias – Bailamos','Ricky Martin – Livin\' La Vida Loca','Gloria Estefan – Conga','Pitbull – International Love','Wisin & Yandel – Abusadora','Romeo Santos – Propuesta Indecente','Carlos Vives – La Bicicleta','Luis Fonsi – Despacito','Nicky Jam – El Perdón','Farruko – Pepas'] },
  { id:4,  series:'sax',      title:'Sax After Dark',      tags:['Late Night','Slow Jams','80–95 BPM','60 Min'],        price:'24.99', tracks:['Jaheim – Could It Be','Joe – All That I Am','R. Kelly – Step in the Name of Love','Ginuwine – Pony','Brandy – Have You Ever','112 – Cupid','Dru Hill – Never Make a Promise','Silk – Freak Me','Jodeci – Cry for You','K-Ci & JoJo – All My Life','Boyz II Men – I\'ll Make Love to You','Aaliyah – Are You That Somebody','Brian McKnight – Back at One','Tyrese – Sweet Lady','Tank – Maybe I Deserve','Usher – Nice & Slow','Next – Wifey','Case – Happily Ever After','Joe – I Wanna Know','Keith Sweat – Twisted'] },
  { id:5,  series:'hiphop',   title:'Hip-Hop Anthems',     tags:['Crowd Anthems','110–125 BPM','60 Min'],               price:'24.99', tracks:['Kendrick Lamar – HUMBLE.','Drake – God\'s Plan','Jay-Z & Kanye – Ni**as in Paris','Cardi B – Bodak Yellow','Migos – Bad and Boujee','Future – Mask Off','21 Savage – Bank Account','Travis Scott – SICKO MODE','Post Malone – Congratulations','Lil Baby – Drip Too Hard','Gunna – Drip Too Hard','DaBaby – Rockstar','Polo G – Pop Out','NBA YoungBoy – Outside Today','Lil Durk – The Voice','Moneybagg Yo – Said Sum','Rod Wave – Heart on Ice','Lil Uzi Vert – XO TOUR Llif3','6ix9ine – GUMMO','Youngboy Never Broke Again – Bandit'] },
  { id:6,  series:'hiphop',   title:'90s Rewind',          tags:['90s','Early 2000s','Nostalgia','100–115 BPM','60 Min'], price:'24.99', tracks:['Biggie – Hypnotize','Tupac – California Love','Jay-Z – Big Pimpin\'','Nas – If I Ruled the World','DMX – Ruff Ryders Anthem','Missy Elliott – Work It','Lil Kim – Not Tonight','Busta Rhymes – Put Your Hands Where My Eyes Could See','Wu-Tang Clan – C.R.E.A.M.','Snoop Dogg – Drop It Like It\'s Hot','Ice Cube – You Can Do It','LL Cool J – Mama Said Knock You Out','Naughty by Nature – Hip Hop Hooray','Warren G – Regulate','Coolio – Gangsta\'s Paradise','Method Man – All I Need','Redman – Da Rockwilder','Outkast – Ms. Jackson','Eve – Let Me Blow Ya Mind'] },
  { id:7,  series:'hiphop',   title:'2K Bombs',            tags:['2000–2010','Club Radio','110–120 BPM','60 Min'],      price:'24.99', tracks:['Nelly – Hot in Herre','Ludacris – Stand Up','Lil Jon – Get Low','T.I. – Whatever You Like','Young Jeezy – Soul Survivor','Gucci Mane – Lemonade','Rick Ross – Hustlin\'','Soulja Boy – Crank That','Fabolous – Throw It in the Bag','Yung Joc – It\'s Goin\' Down','Young Dro – Shoulder Lean','Shop Boyz – Party Like a Rockstar','Mike Jones – Still Tippin\'','Paul Wall – Girl','Three 6 Mafia – Lolli Lolli','Chamillionaire – Ridin\'','T-Pain – Bartender','Bobby V – Slow Down','Lloyd – Get It Shawty'] },
  { id:8,  series:'hiphop',   title:'Check Out My Melody', tags:['Melodic','Crossover','Hooks','95–108 BPM','60 Min'],  price:'24.99', tracks:['Lauryn Hill – Doo Wop','Fugees – Ready or Not','Common – The Light','Mos Def – Ms. Fat Booty','Erykah Badu – On & On','D\'Angelo – Brown Sugar','Outkast – Rosa Parks','A Tribe Called Quest – Can I Kick It?','Maxwell – Ascension','Kanye West – All Falls Down','John Legend – Ordinary People','Alicia Keys – If I Ain\'t Got You','India.Arie – Video','Jill Scott – Golden','Musiq Soulchild – Just Friends','Tweet – Oops','Floetry – Say Yes','Anthony Hamilton – Charlene','Dwele – Without You'] },
  { id:9,  series:'function', title:'Backyard Bounce',     tags:['Cookout','Day Party','100–115 BPM','60 Min'],         price:'24.99', tracks:['OutKast – The Way You Move','Juvenile – Back That Azz Up','Lil Jon – Yeah!','David Banner – Play','UGK – International Players Anthem','Three 6 Mafia – Stay Fly','T-Pain – Buy U a Drank','Flo Rida – Low','Dem Franchize Boyz – Lean wit It','Crime Mob – Knuck If You Buck','Ying Yang Twins – Wait','Do or Die – Po Pimp','Ludacris – Move Bitch','Petey Pablo – Freek-a-leek','Pastor Troy – Are We Cuttin\'','Lil Scrappy – No Problem','YoungBloodZ – Damn!','Twista – Slow Jamz','Trina – Pull Over'] },
  { id:10, series:'function', title:'Poolside Drift',      tags:['Pool Party','Summer Chill','85–100 BPM','60 Min'],    price:'24.99', tracks:['Drake – Hotline Bling','Calvin Harris – Summer','Pharrell – Happy','Justin Timberlake – Can\'t Stop the Feeling','Bruno Mars – Treasure','Dua Lipa – Levitating','Lizzo – Juice','Mark Ronson – Uptown Funk','Daft Punk – Get Lucky','Kygo – Firestone','Zedd – Beautiful Now','The Chainsmokers – Closer','Avicii – Wake Me Up','Martin Garrix – Animals','Disclosure – You & Me','Clean Bandit – Rather Be','Flume – Never Be Like You','Galantis – Runaway','Marshmello – Happier','Sigala – Easy Love'] },
  { id:11, series:'function', title:'Parking Lot Energy',  tags:['Tailgate','Pre-Game','115–130 BPM','60 Min'],        price:'24.99', tracks:['2 Chainz – No Lie','Meek Mill – Started from the Bottom','Big Sean – IDFWU','YG – My Ni**a','Rick Ross – Pop That','Wale – The Need to Know','Yo Gotti – Down in the DM','Young Jeezy – Put On','Future – Same Damn Time','Ace Hood – Trials & Tribulations','French Montana – Choppa Choppa Down','Waka Flocka – Hard in da Paint','Soulja Boy – Kiss Me Thru the Phone','Plies – Bust It Baby','Gucci Mane – I\'m a Dog','T.I. – I\'m Flexin\'','Jeezy – I Do','Yo Gotti – Act Right','Meek Mill – Cold Hearted'] },
  { id:12, series:'function', title:'Low Lights',          tags:['Lounge','Deep House','Smooth','90–105 BPM','60 Min'], price:'24.99', tracks:['Frank Ocean – Thinkin Bout You','The Weeknd – Earned It','SZA – Good Days','H.E.R. – Focus','Jhené Aiko – None of Your Concern','Lucky Daye – Roll Some Mo','Brent Faiyaz – Clouded','Giveon – Heartbreak Anniversary','Daniel Caesar – Best Part','Syd – Body','Kaytranada – 10%','DVSN – With Me','Snoh Aalegra – I Want You Around','Summer Walker – Over It','Ari Lennox – Shea Butter Baby','Khalid – Location','6LACK – PRBLMS','Joyce Wrice – Falling Slowly','Kiana Ledé – Mad at Me'] },
  { id:13, series:'open',     title:'Field Of Dreams',     tags:['Genre-Blending','Curated Chaos','All BPM','60 Min'], price:'24.99', tracks:['Prince – Kiss','Michael Jackson – Billie Jean','Whitney Houston – I Wanna Dance','Rick James – Superfreak','Chaka Khan – Ain\'t Nobody','Donna Summer – Last Dance','Gloria Gaynor – I Will Survive','Earth Wind & Fire – Boogie Wonderland','George Clinton – Atomic Dog','Gap Band – You Dropped a Bomb on Me','Con Funk Shun – Love\'s Train','Zapp – I Want to Be Your Man','Roger – I Want to Be Your Man','Cameo – Word Up','Bar-Kays – Freaky Behavior','Lakeside – Fantastic Voyage','Brick – Dazz','Slave – Just a Touch of Love'] },
  { id:14, series:'open',     title:'Cruise Control',      tags:['Smooth Blend','Any Occasion','90–110 BPM','60 Min'], price:'24.99', tracks:['Sade – Smooth Operator','Anita Baker – Caught Up in the Rapture','Luther Vandross – Never Too Much','Marvin Gaye – Let\'s Get It On','Al Green – Let\'s Stay Together','Barry White – Can\'t Get Enough of Your Love','Maze ft. Frankie Beverly – Before I Let Go','Teddy Pendergrass – Turn Off the Lights','Isley Brothers – Between the Sheets','Commodores – Sail On','Lionel Richie – Hello','Jeffrey Osborne – On the Wings of Love','Peabo Bryson – If Ever You\'re in My Arms Again','Deniece Williams – Let\'s Hear It for the Boy','Natalie Cole – This Will Be','Patti LaBelle – If You Asked Me To'] },
  { id:15, series:'open',     title:'After Hours',         tags:['Late Night','Genre-Blending','85–100 BPM','60 Min'], price:'24.99', tracks:['The Weeknd – Blinding Lights','Drake – Passionfruit','Post Malone – Stay','SZA – The Weekend','Frank Ocean – Nights','6LACK – East Atlanta Love Letter','Bryson Tiller – Exchange','H.E.R. – Best Part','Jhené Aiko – Triggered','Brent Faiyaz – Trust','Summer Walker – Playing Games','Tory Lanez – LUV','Khalid – Talk','Ella Mai – Boo\'d Up','Kehlani – Gangsta','Nav – Price on My Head','Lil Baby – Sum 2 Prove','Don Toliver – After Party','Ty Dolla $ign – Paranoid'] },
  { id:16, series:'open',     title:'Good Vibes Only',     tags:['Feel-Good','Wide Appeal','95–115 BPM','60 Min'],     price:'24.99', tracks:['Pharrell – Happy','Justin Timberlake – Can\'t Stop the Feeling','Bruno Mars – Uptown Funk','Lizzo – Good as Hell','Anderson .Paak – Come Down','Childish Gambino – Redbone','Leon Bridges – Coming Home','Surfaces – Sunday Best','Bill Withers – Lovely Day','Kirk Franklin – Stomp','Stevie Wonder – Signed Sealed Delivered','Earth Wind & Fire – Let\'s Groove','Kool & The Gang – Celebration','Sister Sledge – We Are Family','The O\'Jays – Love Train','Harold Melvin – The Love I Lost','Maze – Joy & Pain','Frankie Beverly – Golden Time of Day','The Isley Brothers – For the Love of You','Van Morrison – Brown Eyed Girl'] },
  { id:17, series:'warmup',   title:'Warm-Up Mix Vol. 1',  tags:['High Energy','Open Format','30 Min'],                price:'24.99', tracks:['Black Eyed Peas – Let\'s Get It Started','Kanye West – Stronger','Eminem – Lose Yourself','Migos – Fight Night','Daddy Yankee – Gasolina','Post Malone & Swae Lee – Sunflower','Bruno Mars & Cardi B – Finesse','Usher & Ludacris – Yeah','Usher & Pitbull – DJ Got Us Fallin In Love','Glass Animals – Heat Waves','Rihanna – Please Don\'t Stop the Music','Dua Lipa – Training Season','Justin Bieber & Nicki Minaj – Beauty and a Beat','Jennifer Lopez & Pitbull – On the Floor','Ke$ha & Pitbull – Timber','Cobra Starship & Sabi – You Make Me Feel','Rihanna – Shut Up and Drive','Flo-Rida & T-Pain – Low','Fergie & Will.I.Am – Fergalicious','Rihanna – We Found Love','Katy Perry & Juicy J – Dark Horse','Flo-Rida & Sage The Gemini – GDFR','Waka Flocka & Roscoe Dash – No Hands','Drake – Trophies','Andy Mineo & Lecrae – Coming In Hot','Jay-Z & Rihanna & Kanye West – Run This Town','T.I. – Bring Em Out'] },
  { id:18, series:'warmup',   title:'Warm-Up Mix Vol. 2',  tags:['High Energy','Open Format','30 Min'],               price:'24.99', tracks:['Pitbull & Ne-Yo – Give Me Everything','LMFAO – Party Rock Anthem','Taio Cruz – Dynamite','Flo Rida – Good Feeling','will.i.am & Britney Spears – Scream & Shout','Macklemore – Can\'t Hold Us','Robin Thicke – Blurred Lines','Pharrell – Happy','Mark Ronson & Bruno Mars – Uptown Funk','Justin Timberlake – Can\'t Stop the Feeling','Meghan Trainor – All About That Bass','Iggy Azalea & Charli XCX – Fancy','Nicki Minaj – Super Bass','Drake – Started From the Bottom','Kanye West – Power','Jay-Z & Alicia Keys – Empire State of Mind','T.I. & Rihanna – Live Your Life','Ludacris & Usher – Yeah!','OutKast – Hey Ya!','Missy Elliott – Work It'] },
  { id:19, series:'warmup',   title:'Warm-Up Mix Vol. 3',  tags:['High Energy','Open Format','30 Min'],               price:'24.99', tracks:['The Weeknd – Can\'t Feel My Face','Drake – Hotline Bling','Kendrick Lamar – HUMBLE.','Cardi B – I Like It','Bruno Mars & Cardi B – Finesse','Post Malone & Swae Lee – Sunflower','Travis Scott – Goosebumps','Dua Lipa – New Rules','Lizzo – Good as Hell','Billie Eilish – bad guy','Ariana Grande – 7 Rings','Ed Sheeran – Shape of You','Bruno Mars – 24K Magic','Jason Derulo – Want to Want Me','Maroon 5 – Sugar','Luis Fonsi & Daddy Yankee – Despacito','J Balvin & Willy William – Mi Gente','Bad Bunny & Drake – MIA','Shakira & Rihanna – Can\'t Remember to Forget You','Ozuna – Taki Taki'] },
  { id:20, series:'warmup',   title:'Warm-Up Mix Vol. 4',  tags:['High Energy','Open Format','30 Min'],               price:'24.99', tracks:['The Weeknd – Blinding Lights','Dua Lipa – Levitating','Harry Styles – As It Was','Olivia Rodrigo – good 4 u','Jack Harlow – First Class','Lizzo – About Damn Time','Doja Cat – Say So','Drake – Toosie Slide','Justin Bieber & The Kid LAROI – Stay','Post Malone – Circles','Lil Nas X – Old Town Road','Megan Thee Stallion – Body','SZA – Shirt','Beyoncé – BREAK MY SOUL','Adele – Easy On Me','Ed Sheeran – Bad Habits','Charlie Puth – Light Switch','Dua Lipa – Don\'t Start Now','Bad Bunny – Me Porto Bonito','J Balvin – In Da Getto'] }
];
